version: '3.4'

services:
  auth_database:
    image: postgres
    container_name: auth_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=auth_server
    restart: always
  authorization:
    build: ./
    container_name: authorization_service
    ports:
      - "9000:9000"
    environment:
      - AUTH_POSTGRES_USER=postgres
      - AUTH_POSTGRES_PASSWORD=123456
#      - POSTGRES_HOST=auth_database
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_DATABASE=auth_server
    depends_on:
      - auth_database
