server:
  port: 9000

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.jdbc: INFO
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DATABASE:auth_server}
    username: ${AUTH_POSTGRES_USER:postgres}
    password: ${AUTH_POSTGRES_PASSWORD:123456}
  liquibase:
    change-log: db-script/auth_server_schema.sql

oauth:
  jwk-set-endpoint: /oauth2/jwks
