server:
  port: 9000

logging:
  level:
#    root: trace
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.jdbc: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_server
    username: postgres
    password: 123456

